language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

install:
  - pip install cookiecutter

script:
  - cookiecutter . --no-input
{% if cookiecutter.use_pytest == 'y' -%}
  - cd ./python_boilerplate && py.test
{% else %}
  - cd ./python_boilerplate && python setup.py test
{% endif %}
